### ISSUE TITLE
Code overflow and support inline code?

### ISSUE THREAD

**Issue by BourneXu** [ijjk/notion-blog#10]
It's better to add `overflow: auto;` into code style to avoid code overflow. I am wondering if this blog could support the inline code ``. Also, I used `<marquee>` for the notion type: callout. This is my personal suggestion.

**Comment by ijjk** [comment]
Hi, thanks for the suggestion. I updated the `code` component with `overflow: auto`. Inline-code from Notion is supported in this example and is applied in the [textBlock renderer](https://github.com/ijjk/notion-blog/blob/5eaeedd71e748a6d9bcefb921f22ea6d8424f47a/src/lib/notion/renderers.ts#L12)
