### ISSUE TITLE
Youtube and other embed media support?

### ISSUE THREAD

**Issue by dingyi** [ijjk/notion-blog#12]
Hi, it seems like I can't render embed Youtube video correctly.

<img width="630" alt="CleanShot 2020-02-21 at 14 01 33@2x" src="https://user-images.githubusercontent.com/2486/75008528-35665700-54b3-11ea-99c3-9d2a29b6916f.png">

**Comment by caarlos0** [comment]
you can use https://www.npmjs.com/package/react-youtube to make it work

**Comment by ijjk** [comment]
Hi, I added examples for rendering embeds from YouTube, Spotify, and Twitter. You can see these in use on this post: https://notion-blog.now.sh/blog/my-second-post

**Comment by dingyi** [comment]
oh thanks for the update, it looks good!
