### ISSUE TITLE
CSS font color inconsistency

### ISSUE THREAD

**Issue by UberVero** [ijjk/notion-blog#17]
I've noticed that the list items gets rendered in a different font color than the paragraph (e.g. [this post](https://blog.veronica.fyi/blog/power-vs-usability)

Any suggestion on how to fix it?

**Comment by ijjk** [comment]
You can apply the `p` styles to the list items too if you want them to match by changing [this line](https://github.com/ijjk/notion-blog/blob/35a6eadbbc7bb797dbc52f7c2b7ea22b70f86e40/src/styles/global.css#L308) to `p, li` or add another style for the `li` to just match the color from that block if desired

**Comment by UberVero** [comment]
Thanks! Fixed. In the future, if I wanted to render the "callout" block in  Notion, what would I need to change? Right now a callout block does not get rendered at all.

**Comment by ijjk** [comment]
Here's an example of what's needed to add support for rendering the callout block [relevant code](https://github.com/ijjk/notion-blog/blob/b741ae96162200cf4174b17009cc5df4adbc50ea/src/pages/blog/%5Bslug%5D.tsx#L245-L257) and example of it being rendered can be viewed on this post: https://notion-blog.now.sh/blog/my-second-post

**Comment by UberVero** [comment]
Thanks @ijjk !
Unfortunately I get an error when I try to deploy:

>Failed to compile.
02:08:21 PM
./src/pages/blog/[slug].tsx
02:08:21 PM
SyntaxError: /zeit/1c2a91a8/src/pages/blog/[slug].tsx: Unexpected token (245:10)
02:08:21 PM
  243 |               break
02:08:21 PM
  244 |           }
02:08:21 PM
> 245 |           case 'callout': {
02:08:21 PM
      |           ^
02:08:21 PM
  246 |               toRender.push(
02:08:21 PM
  247 |                 <div className="callout" key={id}>
02:08:21 PM
  248 |                   {value.format?.page_icon && (
02:08:21 PM
> Build error occurred
02:08:21 PM
Error: > Build failed because of webpack errors
02:08:21 PM
    at build (/zeit/1c2a91a8/node_modules/next/dist/build/index.js:12:900)
02:08:21 PM
error Command failed with exit code 1.
02:08:21 PM
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
02:08:21 PM
Error: Exited with 1
02:08:21 PM
    at ChildProcess.<anonymous> (/zeit/2b7c515595ce4419/.build-utils/node_modules/@now/build-utils/dist/index.js:31347:24)
02:08:21 PM
    at ChildProcess.emit (events.js:223:5)
02:08:21 PM
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
02:08:21 PM
    at maybeClose (internal/child_process.js:1021:16)
02:08:21 PM
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)`

I thought I was missing a `{` but [my slug file](https://github.com/UberVero/mynotionblog/commit/8c0dd3550d88defadf1a1d8d5ba60bde9d72ded8#diff-cd64ac027924dacd5b9a83aed018ddb9) looks exactly like [yours](https://github.com/ijjk/notion-blog/blob/b741ae96162200cf4174b17009cc5df4adbc50ea/src/pages/blog/%5Bslug%5D.tsx#L245-L257).

**Comment by ijjk** [comment]
@UberVero it looks like the extra `{` I added on the `case` above the callout didn't get added in that commit. I added another bracket on [this line](https://github.com/UberVero/mynotionblog/blob/8c0dd3550d88defadf1a1d8d5ba60bde9d72ded8/src/pages/blog/%5Bslug%5D.tsx#L233). It was just for preference, you could remove the closing bracket on [this line](https://github.com/UberVero/mynotionblog/blob/8c0dd3550d88defadf1a1d8d5ba60bde9d72ded8/src/pages/blog/%5Bslug%5D.tsx#L244) if you'd prefer. Sorry for the un-necessary change 😅
