### ISSUE TITLE
Ordering of blog posts in the Notion table

### ISSUE THREAD

**Issue by UberVero** [ijjk/notion-blog#18]
I thought the blog ordered the articles by mirroring the order in Notion, but it doesn't seem to work that way. For example I published a post on March 2nd that looks first in my Notion table (ordered by Date- Ascending) but is at the bottom of the [summary page](https://blog.veronica.fyi/blog).

How to make sure the blog follows the same order of the table?
Thanks!

**Comment by ijjk** [comment]
If I recall correctly Notion returns the data in the order the posts are manually sorted and not by a custom sort applied when viewing. If you want them to be sorted when rendering on the blog I'd recommend copying the sort logic from generating the previews from [here](https://github.com/ijjk/notion-blog/blob/master/src/lib/notion/getBlogIndex.ts#L62-L67) to [here](https://github.com/ijjk/notion-blog/blob/master/src/pages/blog/index.tsx#L33-L35).

**Comment by UberVero** [comment]
Confirming that sorting post manually fixed this.
