### ISSUE TITLE
Should be bumped to the latest version of next

### ISSUE THREAD

**Issue by wbunting** [ijjk/notion-blog#21]
Remove the unstable methods + add preview mode.

@ijjk I took a stab at this on a fork:
https://github.com/wbunting/notion-blog

Adds some api routes to enable / disable preview mode as well as adds a banner to show the user that they are in preview and which posts are drafts.

![image](https://user-images.githubusercontent.com/18180928/76405180-17618780-63cb-11ea-9d35-3dda61ca8d1c.png)

If the changes look good to you I can PR on this repo with the patch.

**Comment by wbunting** [comment]
It would also be pretty sick to get this set up with [Deploy Hooks](https://zeit.co/docs/v2/more/deploy-hooks). That way if your preview looks good you can click "rebuild SSG" or something to sync up to production

**Comment by ijjk** [comment]
Hi, the changes on your fork look awesome, I would definitely appreciate a PR with those changes! 

A few things I noticed that can be updated:

- combine `api/clear-preview` and `api/clear-preview-post` into a single endpoint and redirect to `/blog` if no `slug` query value
- the exit preview mode button looks like it could use `flex-direction: column` to make sure the text is centered vertically
-  the fallback state for lazy blog posts isn't currently handled, we'll want to show a loading state when `useRouter().isFallback` is `true`

Feel free to open the PR and I can help tweak these things if you'd like, thanks for looking into this!
