### ISSUE TITLE
In-page tables, URL Bookmarks not rendered

### ISSUE THREAD

**Issue by rounakdatta** [ijjk/notion-blog#25]
Hello and a big thumbs up to all involved in this project!
I could get my blog set up in minutes, however faced some issues with:

---
- In-page tables
_Notion_
![image](https://user-images.githubusercontent.com/20105014/77826328-bb219600-7134-11ea-8170-58077cad6c1e.png)
_Rendered_
![image](https://user-images.githubusercontent.com/20105014/77826348-d1c7ed00-7134-11ea-9b34-b8c5eef75fae.png)

- URL Bookmarks
_Notion_
![image](https://user-images.githubusercontent.com/20105014/77826388-fb811400-7134-11ea-8e0f-b33525ce06f0.png)
_Rendered_
![image](https://user-images.githubusercontent.com/20105014/77826397-09369980-7135-11ea-92c0-8eded9ec5188.png)

---

So, as shown, these elements are simply going missing. Would love to have some discussion, this would help me to reframe the elements other ways, or if this's expected I could also work on a PR to fix this, thanks! :)

**Comment by besutome** [comment]
I worked
https://github.com/ijjk/notion-blog/pull/64
