### ISSUE TITLE
Existing secret "notion-token" will be used

### ISSUE THREAD

**Issue by furkanacikgoz** [ijjk/notion-blog#29]
Hello there, 

I tried to deploy one time. But I probably entered the wrong token and id. I delete project and try again.
But this time I can't change my token and index-id on vercel

![image](https://user-images.githubusercontent.com/992912/82142146-efffbe80-9842-11ea-9932-1b2a282298cb.png)

Does anyone have a same issue?

**Comment by ijjk** [comment]
Hi, to change theses values you currently need to use the [Vercel CLI](https://www.npmjs.com/package/vercel) or the new [environment variables support](https://vercel.com/blog/environment-variables-ui). 

You should be able to update them with `vercel secrets rm notion-token` and `vercel secrets rm blog-index-id` and then go through the import flow again or add them with the CLI with `vercel secrets add notion-token "YOUR_TOKEN"` and `vercel secrets add blog-index-id "YOUR_PAGE_ID"`
