### ISSUE TITLE
error 'NOTION_TOKEN' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by djtlgucla** [ijjk/notion-blog#3]
C:\Windows\System32\notion-blog>NOTION_TOKEN='2bc970425c03feaafc8ed252b0b7f95f1e0eb122904c66413f5858760149bab4087e5524d07c0748a59169259abf069a9cf4eb64d201e03fa29c02ff30fe650af88fe0e89066bfa38d43246831e9' BLOG_INDEX_ID='20509c6870e74c53a5adff4ce5fa3114' node scripts/create-table.js
'NOTION_TOKEN' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ijjk** [comment]
Hi, on Windows you need to use `set` to set variables in your environment e.g. `set NOTION_TOKEN='my-value'`. See full snippet in readme here https://github.com/ijjk/notion-blog#running-locally
