### ISSUE TITLE
Error while importing on Github integration step

### ISSUE THREAD

**Issue by cem2ran** [ijjk/notion-blog#30]
I'm getting the following error:
![image](https://user-images.githubusercontent.com/959142/82150813-77582c80-9859-11ea-94ac-d0ba0bfc967e.png)

I do observe that the repo is created, but I cannot proceed.

**Comment by leo** [comment]
@cem2ran Thank you for sharing! Would you mind sharing your console logs with us too?

**Comment by cem2ran** [comment]
appears to work now 🤷‍♂️ Maybe it was due to me renaming it to blog instead of notion-blog. Prior to running import I also had a repo named blog, which I deleted. Maybe some caching.
