### ISSUE TITLE
NOTION_TOKEN & BLOG_INDEX_ID references secret that does not exist

### ISSUE THREAD

**Issue by TomTucka** [ijjk/notion-blog#39]
Heya,

Tried to deploy this using vercel, I've set both env vars in vercel `NOTION_TOKEN ` & `BLOG_INDEX_ID `, and I'm getting this error for both tokens

```
Environment Variable "BLOG_INDEX_ID" references Secret "blog-index-id", which does not exist.
Environment Variable "NOTION_TOKEN" references Secret "notion-token", which does not exist.
```

I got the `BLOG_INDEX_ID ` from the URL on Notion and the `NOTION_TOKEN ` from the token_v2 cookie in chrome dev tools. Are you able to help me troubleshoot this issue?

**Comment by ijjk** [comment]
Hi, I updated the config for this project to no longer specify these values as required in the `now.json` file since they can be configured in your project instead now. Can you give deploying via [this link](https://vercel.com/import/settings?s=https://github.com/ijjk/notion-blog/tree/master&env=NOTION_TOKEN,BLOG_INDEX_ID&envDescription=Required+env+values+for+deploying&envLink=https://github.com/ijjk/notion-blog%23getting-blog-index-and-token) a try and let me know if that works alright for you?

**Comment by TomTucka** [comment]
Heya,
I put the values in for the required env vars, I left everything else like this:
![9e34b20ec6a60e687a265b6d0b201647](https://user-images.githubusercontent.com/3950254/86055391-97cbf700-ba53-11ea-8df8-233bec4b514a.png)

and I got this error: `The repository "notion-blog" couldn't be found in your linked GitHub account.`
I created the repository on my GitHub account and then I got this: `An unexpected internal error occurred`


It creates the project in Vercel, but it's not deploying anything and the repo I created is still empty

**Comment by ijjk** [comment]
@TomTucka thanks for trying that link, I've shared this with our team and we are investigating the errors you encountered

**Comment by ijjk** [comment]
@TomTucka We identified a problem with the flow which should be resolved now, could you try once more with [this import URL](https://vercel.com/import/git?s=https://github.com/ijjk/notion-blog/tree/master&env=NOTION_TOKEN,BLOG_INDEX_ID&envDescription=Required+env+values+for+deploying&envLink=https://github.com/ijjk/notion-blog%23getting-blog-index-and-token) and let me know how it goes?

**Comment by TomTucka** [comment]
@ijjk Awesome, that worked! Thanks for the help 🙂

**Comment by ijjk** [comment]
No problem, thanks for giving it another go! I'm gonna close this issue since it should be resolved now
