### ISSUE TITLE
Fast refresh doesn't seem to be enabled after updating next package

### ISSUE THREAD

**Issue by baptisteArno** [ijjk/notion-blog#54]
First of all, thank you for this amazing template.

I updated next package to 10.x with the hope to have fast refresh enabled but it seems it doesn't fast refresh. Any idea why?

**Comment by ijjk** [comment]
Closing as this should be resolved now. It was due to components not being named properly. Related documentation here https://nextjs.org/docs/basic-features/fast-refresh#limitations
