### ISSUE TITLE
How to open RSS?

### ISSUE THREAD

**Issue by hu00yan** [ijjk/notion-blog#55]
Just find a file:  src/lib/build-rss.ts, looks like RSS feed will automatically generate. How to open or use it?

**Comment by Lonor** [comment]
The build script [build-rss.ts](https://github.com/ijjk/notion-blog/blob/master/src/lib/build-rss.ts) will be generated during the build time and it's artifact called `atom` produced in the public directory which means you can visit the path `/atom` to open.

看一下 Build logs 就知道了。
