### ISSUE TITLE
Failed to load Notion posts

### ISSUE THREAD

**Issue by Lonor** [ijjk/notion-blog#61]
Hey, I just found that the notion blog posts became empty. The site https://notion-blog.vercel.app/blog shows nothing. Could it be that the Notion's API is not accessible anymore? or they changed the response structure or something else. I have tried to use the latest notion token and it doesn't work either.

**Comment by skmatz** [comment]
Same problem.
Notion API has probably changed.
With reference to [this issue](https://github.com/jamalex/notion-py/issues/292), it seems that the maximum value of the pagination limit has changed.

**Comment by skmatz** [comment]
I solved this problem with change `limit` from 999 to 100.
https://github.com/ijjk/notion-blog/blob/7b39503232b98a6644f09daae61abf47533b5720/src/lib/notion/getBlogIndex.ts#L26

**Comment by Lonor** [comment]
> I solved this problem by changing `limit` from 999 to 100.
> https://github.com/ijjk/notion-blog/blob/7b39503232b98a6644f09daae61abf47533b5720/src/lib/notion/getBlogIndex.ts#L26

Yeah, it works! Thank you.

**Comment by dnnaji** [comment]
Worked for me as well.

**Comment by Lonor** [comment]
OK then I'll make a pull request from @skmatz patch file of https://github.com/skmatz/vml-blog/pull/2 .
