### ISSUE TITLE
API /loadPageChunk no longer used by notion

### ISSUE THREAD

**Issue by yusriyunus** [ijjk/notion-blog#66]
Hi! I try to reverse engineer notion API and it turns out that notion using /loadCachedPageChunk instead of  /loadPageChunk. I think we need to update this lib. Thanks

**Comment by ijjk** [comment]
It appears to be working still, if you're encountering trouble with the existing data loading feel free to open a PR updating the endpoint name! 

Going to close this since it doesn't currently seem to be a problem.

**Comment by sidtr0** [comment]
I have a problem with this. I can't find `loadPageChunk` on the network tab, only `loadCachedPageChunk`. Was there any workaround for this?
