### ISSUE TITLE
Sao pres Zeit button thats it?

### ISSUE THREAD

**Issue by daledali** [ijjk/notion-blog#7]
It says to press on Zeit one-click button OR the following. So if we press Zeit we don't need to enter the token anywhere? In can't find the notion page

**Comment by ijjk** [comment]
Hi, when you click the deploy button you should see a screen like below that asks you to enter your Notion token and the id of the page in Notion you want to use for you blog. The first time you access `/blog` or build the application it will create the table for you in Notion on the provided page

<img width="1419" alt="deploy-screenshot" src="https://user-images.githubusercontent.com/22380829/74194102-37f8bf00-4c1e-11ea-8d68-082b65d08187.png">
