### ISSUE TITLE
sitemap and RSS generation

### ISSUE THREAD

**Issue by fqure** [ijjk/notion-blog#73]
This is in [general nextjs/Vercel](https://github.com/vercel/next.js/discussions/12209) but how can something like this be put into the current notion-blog ?

**Comment by ijjk** [comment]
Hi, you can build a sitemap in a similar way to how the rss feed is being generated [in this file](https://github.com/ijjk/notion-blog/blob/b35fcbc5c52d93bb7af8400a3f15d197690f8b48/src/lib/build-rss.ts). 

If you would like it to dynamically update as pages are added via [ISR](https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration) you can add an API route with `stale-wile-revalidate` to generate the sitemap dynamically. Docs are coming soon for this [here](https://github.com/vercel/next.js/pull/28346)
