### ISSUE TITLE
Unable to generate notion token

### ISSUE THREAD

**Issue by nisarhassan12** [ijjk/notion-blog#8]
When i run `NOTION_TOKEN='token' BLOG_INDEX_ID='new-page-id' node scripts/create-table.js`
I get this:
![image](https://user-images.githubusercontent.com/46004116/74802885-ec6ca200-52fc-11ea-95c4-2f0af671b024.png)

**Comment by ijjk** [comment]
The `BLOG_INDEX_ID` and `NOTION_TOKEN` both come from Notion. See [this section](https://github.com/ijjk/notion-blog#getting-blog-index-and-token) in the readme for details on finding these values
